    - name: Build and Push Docker Image
      run: |
        cd helm/rick-and-morty-api
        docker build -t ghcr.io/${{ github.repository_owner }}/rickmorty-app:latest .
        docker push ghcr.io/${{ github.repository_owner }}/rickmorty-app:latest

    - name: Deploy with Helm
      run: |
        helm upgrade --install rickmorty ./helm/rick-and-morty-api \
          --set image.repository=ghcr.io/${{ github.repository_owner }}/rickmorty-app \
          --set image.tag=latest
